config/routes.rb
Rails.application.routes.draw do
  root to: "users#show"

  namespace :api do
    namespace :v1 do
      resources :games, except: [:edit, :new], defaults: { format: :json }
    end
  end
  resources :games, only: [:index]

  resources :users, only: [:index, :create]

  get "/dashboard", to: "users#show", as: "dashboard"
  get '/auth/github', as: "github_login"
  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/:game_slug', to: 'games#show', as: "game"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :users, dependent: :destroy

  before_save :create_slug

  validates :github_url, url: true, presence: true
  validates :name, presence: true
  validates :screenshot_or_gif, presence: true
  validates :heroku_url, url: true, presence: true

  def create_slug
    self.slug = self.name.parameterize
  end

  def owner
    github_url.split("/")[-2]
  end

  def repo
    github_url.split("/")[-1]
  end
end

app/models/github.rb
class Github < OpenStruct

  def self.service
    GithubService.new
  end

  def self.find_collaborators(owner, repo)
    collaborators = service.find_collaborators(owner, repo)
      collaborators.map do |collaborator|

        Github.new(collaborator)
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :game

  validates :username, presence: true, uniqueness: true

  enum role: { default: 0 , business_admin: 1 }

  def self.from_omniauth(auth_info)
    User.find_or_create_by(uid: auth_info.uid) do |new_user|
      new_user.uid                = auth_info.uid
      new_user.username           = auth_info.info.nickname
      new_user.avatar             = auth_info.info.image
      new_user.oauth_token        = auth_info.credentials.token
      new_user.role               = "default"
      new_user.game_id            = 1
    end
  end

  def self.assign_game(current_user_id, id)
    user = User.find(current_user_id)
    user.update(game_id: id)
    user.save
  end


end

app/controllers/api/v1/games_controller.rb
class Api::V1::GamesController < ApiBaseController

  def index
    render json: Game.all
  end

  def show
    render json: Game.find(params[:id])
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      User.assign_game(current_user.id, @game.id)
      render json: @game
    else
      render json: { errors: @game.errors }, status: 500
    end
  end

  def update
    game = Game.find(game_params[:id])
    render json: game.update(game_params)
  end

  def destroy
    render json: Game.destroy(params[:id])
  end

  private
    def game_params
      params.require(:game).permit(:name, :github_url, :heroku_url, :screenshot_or_gif, :id)
    end
end

app/controllers/api_base_controller.rb
class ApiBaseController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.where.not(id: 1)
  end

  def show
    @game = Game.find_by(slug: params[:game_slug])
    @collaborators = Github.find_collaborators(@game.owner, @game.repo)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
   user = User.from_omniauth(request.env["omniauth.auth"])
    if user
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_collaborators.html.erb
<div class="collaborators">
  <h4>Collaborators on this Game: </h4>
    <% @collaborators.each do |collaborator| %>
      <div class="collab-card">
        <span><%= image_tag collaborator.avatar_url, class: "collab-image" %></span>
        <h5><%= collaborator.login %></h5>
          <%= link_to "Github Url", collaborator.html_url %>
      </div>
    <% end %>
</div>

app/views/games/_update_game_form.html.erb
<div class="form-group" id="update-game-form">
<p>Want to update or delete your game? </br>
  If you do not wish to update a parameter, leave it as is:</p>
  <input class="form-control hidden" type="text" id="current-user" value="<%= current_user.id %>">
  <input class="form-control" type="text" id="game-name" value="<%= @game.name %>">
  <input class="form-control" type="url" id="game-heroku" value="<%= @game.heroku_url %>">
  <input class="form-control" type="url" id="game-github" value="<%= @game.github_url %>">
  <input class="form-control" type="url" id="game-screenshot" value= "<%= @game.screenshot_or_gif %>">
  <input class="btn btn-default pull-right" id="update-game" type="button" name="submit" value="Update My Game!">
  <input class="btn btn-default pull-right" id="destroy-game" type="button" name="submit" value="Delete My Game!">
</div>

app/views/games/index.html.erb
<div class="header">
  <h1 class="index-header">All Gametime Games</h1>
</div>
<div id="latest-games">
  <% @games.each do |game| %>
  <ul class="list-group col-md-3">
    <li class="list-group-item"><%= link_to game.name, game_path(game.slug) %></li>
    <li class="list-group-item"><%= link_to "Play the Game!", game.heroku_url, target: "_blank" %></li>
    <li class="list-group-item"><%= link_to "Check out the Code!", game.github_url, target: "_blank" %></li>
    <li class="list-group-item"><%= image_tag game.screenshot_or_gif %></li>
  </ul>
  <% end %>
</div>

app/views/games/show.html.erb
<div class="container" id="standard-game">
  <div class="game-show" data-game-id="<%= @game.id %>">
    <span class="game-title"><h1><%= @game.name %></h1>
    <div class="game-image"><%= image_tag @game.screenshot_or_gif, id: "game-image" %></div></span>
    <div class="wrapper-game">
      <% unless @game.nil? %>
        <a class="play-link" href="<%= @game.heroku_url %>" target="_blank">Play The Game!</a>
      <% end %>
    </div>
    <%= render partial: "collaborators" %></br>
    <div class="alumni">
      <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
      <%= link_to "Looking to hire a graduate? View our Alumni portfolios", "https://www.turing.io/alumni", target: "_blank"%>
      <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
    </div>
  </div>
  <div id="game-content">
    <% if @game.users.include?(current_user) %>
    <%= render partial: "update_game_form" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Turing Arcade</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <link href="https://fonts.googleapis.com/css?family=Press+Start+2P|Aldrich" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: "shared/navbar" %>
      <%= yield %>
    <%= javascript_include_tag 'application' %>
    <div class="gap"></div>
    <nav class="navbar navbar-default navbar-fixed-bottom" id="footer">
      <div class="container">
        <p>Copyright &copy; Turing Arcade</p>
      </div>
    </nav>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default poop-bar">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><%= link_to "Turing Arcade", dashboard_path, id: "main-header" %></li>
      <li><%= link_to image_tag('http://ordinarysuperhero.com/wp-content/uploads/2009/08/mushroom_grid.gif', class: "mushroom-img"), games_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right" id="right-nav">
      <li><%= link_to "All The Games", games_path, style: "color: green" %></li>
      <% if !current_user %>
        <li><%= link_to "Sign in with Github", github_login_path, style: "color: green", class: "css_class"%></li>
      <% end %>
      <% if current_user %>
      <li><%= link_to "Dashboard", dashboard_path(current_user), style: "color: green"  %></li>
      <li><%= link_to "Logout", logout_path, method: :delete, style: "color: green", class: "css_class" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/_new_game_form.html.erb
  <ul id="one-game">

  </ul>
  <p>Want to add your game?<p>
  <div class="form-group" id="new-game">
    <input class="form-control hidden" type="text" id="current-user" value="<%= current_user.id %>">
    <input class="form-control hidden" type="text" id="current-role" value="<%= current_user.role %>">
    <input class="form-control" type="text" id="game-name" placeholder="Name">
    <input class="form-control" type="url" id="game-heroku" placeholder="Game Link: Must be the full url">
    <input class="form-control" type="url" id="game-github" placeholder="Github URL: Must be the full url">
    <input class="form-control" type="url" id="game-screenshot" placeholder="Gif: Must be the full url">
    <input class="form-control" type="text" id="game-check" placeholder="What is the wifi password at Turing?">
    <input class="btn btn-default pull-right" id="create-game" type="button" name="submit" value="Add My Game!">
  </div>

app/views/users/show.html.erb
<% if @user %>
  <div class="user-show" id="welcome">
    <h2>Welcome, <%= @user.username %></h2>
    <h3><%= "#{@user.username}'s Games" %></h3>
    <% if @user.game.id == 1 %>
    <p>You have no games</p>
      <%= render partial: 'new_game_form' %>
    <% else %>
      <ul>
        <li><%= link_to @user.game.name, game_path(@user.game.slug) %></li>
      </ul>
    <% end %></br>
  </div>
<% else %>
  <div id="guest-login">
    <p> The Turing Arcade was created as a portal for games created by <%= link_to 'Turing', 'https://www.turing.io/', target: 'blank' %> Students.</br></br>
      To see the work our students have done:</br></br>
    <%= link_to "Browse All Games", games_path, style: "color: black", class: "browse_css_class"%></br></br>
    To add your own game, you must sign in through <%= link_to 'github', github_login_path %>.</p>
  </div>
<% end %>